// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-social/internal/service/internal/dao/internal"
)

// internalPraiseDao is internal type for wrapping internal DAO implements.
type internalPraiseDao = *internal.PraiseDao

// praiseDao is the data access object for table praise.
// You can define custom methods on it to extend its functionality as you wish.
type praiseDao struct {
	internalPraiseDao
}

var (
	// Praise is globally public accessible object for table praise operations.
	Praise = praiseDao{
		internal.NewPraiseDao(),
	}
)

// Fill with you ideas below.
