// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Article is the golang structure of table article for DAO operations like Where/Data.
type Article struct {
	g.Meta     `orm:"table:article, do:true"`
	Id         interface{} // 文章id
	Title      interface{} // 文章标题
	Content    interface{} // 文章内容
	Img        interface{} // 文章图片地址
	CommentNum interface{} // 评论数
	PraiseNum  interface{} // 点赞数
	Uid        interface{} // 作者id
	State      interface{} // 状态 1正常 9:删除
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
}
