// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Comment is the golang structure of table comment for DAO operations like Where/Data.
type Comment struct {
	g.Meta      `orm:"table:comment, do:true"`
	Id          interface{} // 评论id
	Aid         interface{} // 文章id
	Uid         interface{} // 评论用户id
	CommentCont interface{} // 评论内容
	ToUid       interface{} // 被评论用户id
	State       interface{} // 状态 1:正常 9:删除
	PraiseNum   interface{} // 点赞数
	CreateTime  interface{} // 创建时间
	UpdateTime  interface{} // 更新时间
}
