// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Praise is the golang structure of table praise for DAO operations like Where/Data.
type Praise struct {
	g.Meta     `orm:"table:praise, do:true"`
	Id         interface{} // 点赞id
	Uid        interface{} // 点赞用户id
	Aid        interface{} // 文章id
	ToUid      interface{} // 被点赞者用户id
	Type       interface{} // 点赞类型  1:文章点赞 2:评论点赞
	TypeId     interface{} // 对应文章或评论id
	State      interface{} // 点赞状态 1:正常 2:取消
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
}
