// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Test is the golang structure of table test for DAO operations like Where/Data.
type Test struct {
	g.Meta `orm:"table:test, do:true"`
	Id     interface{} //
}
