// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	Id         interface{} // 用户ID
	NickName   interface{} // 昵称
	Avatar     interface{} // 头像
	Gender     interface{} // 性别 0:保密 1:男 2:女
	Type       interface{} // 用户类型 0:普通用户 1:运营用户
	Phone      interface{} // 手机号
	PassWord   interface{} // 密码md5
	CreateTime interface{} // 创建时间
	UpdateTime interface{} // 更新时间
}
