// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Article is the golang structure for table article.
type Article struct {
	Id         int    `json:"id"         description:"文章id"`
	Title      string `json:"title"      description:"文章标题"`
	Content    string `json:"content"    description:"文章内容"`
	Img        string `json:"img"        description:"文章图片地址"`
	CommentNum int    `json:"commentNum" description:"评论数"`
	PraiseNum  int    `json:"praiseNum"  description:"点赞数"`
	Uid        int    `json:"uid"        description:"作者id"`
	State      int    `json:"state"      description:"状态 1正常 9:删除"`
	CreateTime int64  `json:"createTime" description:"创建时间"`
	UpdateTime int64  `json:"updateTime" description:"更新时间"`
}
