// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Comment is the golang structure for table comment.
type Comment struct {
	Id          int    `json:"id"          description:"评论id"`
	Aid         int    `json:"aid"         description:"文章id"`
	Uid         int    `json:"uid"         description:"评论用户id"`
	CommentCont string `json:"commentCont" description:"评论内容"`
	ToUid       int    `json:"toUid"       description:"被评论用户id"`
	State       int    `json:"state"       description:"状态 1:正常 9:删除"`
	PraiseNum   int    `json:"praiseNum"   description:"点赞数"`
	CreateTime  int64  `json:"createTime"  description:"创建时间"`
	UpdateTime  int64  `json:"updateTime"  description:"更新时间"`
}
