// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Praise is the golang structure for table praise.
type Praise struct {
	Id         int   `json:"id"         description:"点赞id"`
	Uid        int   `json:"uid"        description:"点赞用户id"`
	Aid        int   `json:"aid"        description:"文章id"`
	ToUid      int   `json:"toUid"      description:"被点赞者用户id"`
	Type       int   `json:"type"       description:"点赞类型  1:文章点赞 2:评论点赞"`
	TypeId     int   `json:"typeId"     description:"对应文章或评论id"`
	State      int   `json:"state"      description:"点赞状态 1:正常 2:取消"`
	CreateTime int64 `json:"createTime" description:"创建时间"`
	UpdateTime int64 `json:"updateTime" description:"更新时间"`
}
