// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Test is the golang structure for table test.
type Test struct {
	Id string `json:"id" ` //
}
