// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id         int64  `json:"id"         description:"用户ID"`
	NickName   string `json:"nickName"   description:"昵称"`
	Avatar     string `json:"avatar"     description:"头像"`
	Gender     int    `json:"gender"     description:"性别 0:保密 1:男 2:女"`
	Type       int    `json:"type"       description:"用户类型 0:普通用户 1:运营用户"`
	Phone      string `json:"phone"      description:"手机号"`
	PassWord   string `json:"passWord"   description:"密码md5"`
	CreateTime int64  `json:"createTime" description:"创建时间"`
	UpdateTime int64  `json:"updateTime" description:"更新时间"`
}
